# 
# Copyright (C) 2020  CismonX <admin@cismon.net>
# 
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty, provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
# 

set tool "default"
set timeout 5
global B64_ENCODE

set rand_str_list { }
for { set i 100 } { $i < 200 } { incr i } {
    lappend rand_str_list [ exec head -c $i /dev/urandom | base64 $B64_ENCODE ]
}

u6a_run "```s`d`@|i`ci" - - 1
for { set i 0 } { $i < [ llength $rand_str_list ] } { incr i } {
    set rand_str [ lindex $rand_str_list $i ]
    send -- "$rand_str\r"
    expect {
        -ex "$rand_str" {
            pass "case $i ok!"
        }
        default {
            fail "case $i fails!"
        }
    }
}
u6a_stop 1
